basic option parsing working. started working on processing env variables

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -3,27 +3,43 @@
 # Stop secution as soon as there is any error
 set -e
 
-usage() {
+function usage {
   cat <<EOF
 
   Usage: deploy <options> <mode>
 
   Options:
     -u <github-user>            The GitHub user
-    -r <github-repo>            The GithUb repo name
+    -r <github-repo>            The GithUb repo
     -t <github-tag>             The GitHub tag to be deployed
-    -p <procname>               The PM2 process-name to be (re)started
+    -p <pm2-app>                The PM2 app name
+    -e <file/"name val">        The environment variables to be set for PM2.
+                                This can either specify a file containing all 
+                                environment variables (format: name val\n) or
+                                multiple instances of -e can be used to set 
+                                individual env variables
 
   Modes:
-    -m setup|update|rollback    setup: Performs initial setup before starting the app
-                                update: Only updates the app to the specified tag
+    -m deploy|rollback          deploy (default): Performs fresh deployment
                                 rollback: Rollsback to previous deployment
 
 EOF
 }
 
+PM2_ENV=""
+function process_env {
+  arg = $1
+  if [[ -f $1 ]]; then
+    
+  else
+
+    PM2_ENV=$PM2_ENV
+  fi
+}
+
+MODE="deploy"
 # process commandline argument
-while getopts ":urtpm" opt; do 
+while getopts ":u:r:t:p:m:" opt; do 
   case $opt in
     u)
       GITHUB_USER=$OPTARG
@@ -40,6 +56,9 @@ while getopts ":urtpm" opt; do
     m)
       MODE=$OPTARG
     ;;
+    e)
+      process_env $OPTARG
+    ;;
     \?)
       echo "Invalid option: -$OPTARG";
       exit 1
@@ -50,28 +69,66 @@ while getopts ":urtpm" opt; do
   esac
 done
 
+if [[ -z $GITHUB_USER ]]; then
+  echo "ERROR: GitHub user not specified"
+  usage
+  exit 1
+fi
+
+if [[ -z $GITHUB_REPO ]]; then
+  echo "ERROR: GitHub repo not specified"
+  usage
+  exit 1
+fi
+
+if [[ -z $GITHUB_TAG ]]; then
+  echo "ERROR: GitHub tag not specified"
+  usage
+  exit 1
+fi
+
+if [[ -z $PM2_APP_NAME ]]; then
+  echo "ERROR: PM2 process-name not specified"
+  usage
+  exit 1
+fi
+
+if [ $MODE != 'deploy' ] && [$MODE != 'rollback']; then
+  echo "ERROR: GitHub user not specified"
+  usage
+  exit 1
+fi
+
 # LATEST_URL="https://github.com/journeymanavi/apartment-uncomplex-api/releases/latest"
 # REDIRECTED_LATEST_URL="https://github.com/journeymanavi/apartment-uncomplex-api/releases/tag/v0.0.2"
 DEPLOY_DIR=${GITHUB_REPO}-${GITHUB_TAG}
 DEPLOY_FILE=${DEPLOY_DIR}.tar.gz
 ARTIFACT_URL="https://github.com/${GITHUB_USER}/${GITHUB_REPO}/releases/download/${GITHUB_TAG}/${DEPLOY_FILE}"
 
-echo "GITHUB_USER:      ".$GITHUB_USER
-echo "GITHUB_REPO:      ".$GITHUB_REPO
-echo "GITHUB_TAG:       ".$GITHUB_TAG
-echo "DEPLOY_DIR:       ".$DEPLOY_DIR
-echo "DEPLOY_FILE:      ".$DEPLOY_FILE
-echo "ARTIFACT_URL:     ".$ARTIFACT_URL
+echo "GITHUB_USER:      "${GITHUB_USER}
+echo "GITHUB_REPO:      "${GITHUB_REPO}
+echo "GITHUB_TAG:       "${GITHUB_TAG}
+echo "PM2_APP_NAME:     "${PM2_APP_NAME}
+echo "PM2_ECOSYSTEM:    "${PM2_APP_NAME}
+echo "DEPLOY_DIR:       "${DEPLOY_DIR}
+echo "DEPLOY_FILE:      "${DEPLOY_FILE}
+echo "ARTIFACT_URL:     "${ARTIFACT_URL}
 
 # Print commands before executing
 set -x
 
-echo "Ha Ha"
+# Create directories as needed
+if [[ ! -d $PM2_APP_NAME ]]; then
+  mkdir $PM2_APP_NAME
+else
+  rm -fr $PM2_APP_NAME/$DEPLOY_DIR
+  mkdir $DEPLOY_DIR
+fi
+
+exit 1
 
 # Fetch deployment artefacts
-rm -fr $DEPLOY_DIR
-mkdir $DEPLOY_DIR
-curl -sL $ARTIFACT_URL -o ${DEPLOY_DIR}/${DEPLOY_FILE}
+curl -sL $ARTIFACT_URL -o $PM2_APP_NAME/${DEPLOY_DIR}/${DEPLOY_FILE}
 
 # Extract the fetched artefacts
 tar -xf $DEPLOY_DIR/$DEPLOY_FILE -C $DEPLOY_DIR
